# Generated by Django 2.0.3 on 2018-03-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(help_text='Write yours date ofbirth')),
                ('email', models.EmailField(help_text='Write yours email', max_length=64, unique=True)),
                ('phone', models.CharField(help_text='Write yours phone', max_length=12, unique=True)),
                ('address', models.CharField(blank=True, help_text='Write yours adress', max_length=244, null=True)),
                ('skype', models.CharField(blank=True, help_text='Write yours skype', max_length=64, null=True)),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
