# Generated by Django 2.0.3 on 2018-03-27 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Famale')], max_length=1)),
                ('phone', models.CharField(help_text='Write your mobile number', max_length=64)),
                ('address', models.CharField(blank=True, help_text='Write your address ', max_length=128, null=True)),
                ('skype', models.CharField(blank=True, help_text='Write your skype number', max_length=64, null=True)),
                ('description', models.TextField(blank=True, help_text='Full description of the course', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
